error: store Rust enum types in Error struct
Convert from the C type at time of construction, not time of access

Signed-off-by: Daniel P. Berrangé <berrange@redhat.com>