error: convert ErrorDomain & ErrorNumber to wrapped enums
This change exposes the raw C enum value in cases where there is no
defined Rust enum constant mapping.

The ErrorLevel enum is left unwrapped. Of the existing values, only
'Error' is ever used, 'Warning' has never been used, and it is not
likely further levels will ever be defined.

Signed-off-by: Daniel P. Berrangé <berrange@redhat.com>